### ISSUE TITLE
Allow to setup connection settings as URI

### ISSUE THREAD

**Issue by KingCrunch** [symfony/swiftmailer-bundle#101]
It would be nice, if one can configure one connection with a single string (URI, ...) instead of multiple separate configuration keys

    smtp://user:pass@host

**Comment by sstok** [comment]
But how will that work for more complex transporters? :)

**Comment by KingCrunch** [comment]
@sstok Not like this :) I didn't intended to replace the existing setup, but to allow to simplify it (as long as it makes sense and works). Do you have an example of a transport, that may not work=
