### ISSUE TITLE
SwiftMailer not send mail with Google App account

### ISSUE THREAD

**Issue by frasodel** [symfony/swiftmailer-bundle#106]
I'm using Symfony and I'm trying to send an email with swiftmailer. I have an account set up with google app (produccion@mydomain.com) and when I try to send shows me the following error:

```
Failed to authenticate on SMTP server with username "produccion@mydomain.com" using 2 possible authenticators
```

I tried it with my personal gmail account and send the message correctly with the same settings. Just change the username and password.

```
# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      smtp.gmail.com
    username:  produccion@mydomain.com   #email@gmail.com
    password:  google_app_password       #gmail_password
    auth_mode: login
    port:      587
    encryption: tls
```

I've been searching the internet and I've found this page from Google, where I can change the access to less secure applications. https://www.google.com/settings/security/lesssecureapps

In my gmail account this option is active, but if I turn shows me the same error when sending email. I've been trying to change this setting in google app account but it tells me that this option is not available for google app.

Any idea to send emails from this account by google app? I have to set something else?

**Comment by sstok** [comment]
It seems Gmail prefers OAuth, Swiftmailer supports this authentication mech but its not really documented.

https://developers.google.com/gmail/xoauth2_protocol
https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Transport/Esmtp/Auth/XOAuth2Authenticator.php

**Comment by frasodel** [comment]
Hello @sstok ,

I have modified the parameters of symfony swiftmailer to change the `auth_mode`. I have changed the following code, but I get an error in the kernel application. What `auth_mode` should I use ?

```
# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      smtp.gmail.com
    username:  produccion@mydomain.com   #email@gmail.com
    password:  google_app_password       #gmail_password
    auth_mode: oauth
    port:      587
    encryption: tls
```

This is the error message:
```
InvalidConfigurationException in BaseNode.php line 313:
Invalid configuration for path "swiftmailer.mailers.default.auth_mode": The "OAuth" authentication mode is not supported
```

**Comment by frasodel** [comment]
I have also tried to change it using this code but it tells me that this method is not available

```
// switch to new settings
        $transport      = $this->get('mailer')->getTransport();
        $ext            = $transport->getExtensionHandlers();
        $auth_handler   = $ext[0];
        $auth_handler->setUserName(EMAIL);
        $auth_handler->setPassword(PASSWORD);
        $auth_handler->setAuthMode('XOAUTH2');
```

**Comment by dpcat237** [comment]
I have same problem. I tried `Swift_Message::newInstance('smtp.gmail.com', 465, 'ssl')` without success. I tried with same parameters `https://github.com/PHPMailer/PHPMailer` and it works.

**Comment by Aerendir** [comment]
I'm having the same exact problem. Reading this I don't understand how to solve the problem and also the reworded documentation is not much clear. There is told

> If your application uses tls encryption or oauth authentication, you must override the default options by defining the encryption and auth_mode parameters.

but using as settings

    disable_delivery:  false
    transport: gmail
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: ssl
    auth_mode: oauth

I receive the following exception:

> Invalid configuration for path "swiftmailer.mailers.default.auth_mode": The "oauth" authentication mode is not supported

So, how can I use SwiftMailer with a Google Apps set email?

**Comment by frasodel** [comment]
I could make it work with the following code:

```
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    auth_mode: "%mailer_auth_mode%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
```
and the following parameters:
```
mailer_transport: smtp
    mailer_host: smtp.gmail.com
    mailer_user: ******@*******
    mailer_password: ********
    mailer_auth_mode: login
    mailer_port: 587
    mailer_encryption: tls
```

I do not remember if I had to touch something in connection permissions of the account. But as I have a business account would not let me set some parameters.

**Comment by Aerendir** [comment]
Thankyou for the reply @frasodel ... Anyway in the meantime I've moved to AWS SES to send e-mails, so I solved the problem at root :D
