### ISSUE TITLE
Override defaults

### ISSUE THREAD

**Issue by dTHQb** [symfony/swiftmailer-bundle#107]
I am having a problem where Swiftmailer is attaching a text\plain section to the mail when I am only defining a html mail.

This cause a blank mail when a user uses a text only mail engine. I know that it will be optimal that a text mail is also defined but is there a way to tell the mailer if no text variant is defined use the html mail and strip the html tags?

I can't seem to find any posts regarding this.

Please advise

**Comment by stof** [comment]
This should be opened on the swiftmailer repo itself, not on the bundle. Otherwise the Swiftmailer maintainers will not see the issue, and they are the ones able to answer you.
