### ISSUE TITLE
Mailer options with multiple mailers

### ISSUE THREAD

**Issue by xelan** [symfony/swiftmailer-bundle#111]
When a mailer option like disable_delivery is set for an environment, it is only applied to the default mailer. For example, my config_test.yml contains

```
swiftmailer:
    disable_delivery:  true
```

However, in my opinion delivery should be disabled for all mailers when running in the test environment.

```
php app/console debug:swiftmailer --env=test
[swiftmailer] Current mailers
Name                     Transport Spool Delivery Single Address
mailer2                  smtp      NO    YES      
default (default mailer) smtp      YES   NO       
```

The delivery_address option also behaves like that, it seems to be set only for the default mailer. In the [manual](http://symfony.com/doc/current/reference/configuration/swiftmailer.html#using-multiple-mailers) no such behaviour is documented.

What is the recommended way to ensure that all mailers get the same disable_delivery and delivery_address options depending on the environment?

Thank you very much!

**Comment by stof** [comment]
options are always per mailer. If you use the short syntax to configure it, it applies only to the mailer named ``default``.

If you configure multiple mailers, you need to use the multiple mailer too to disable them all:

```yaml
swiftmailer:
    mailers:
        default:
            disable_delivery:  true
        default2:
            disable_delivery:  true
```

The short syntax is just a convenience for the case where you configure a single mailer (everything gets moved into ``mailers > default``.

**Comment by xelan** [comment]
Thank you very much for your fast response! I added the suggested configuration and it is working fine :thumbsup: However, I still think this behaviour should be mentioned in the docs. Otherwise, users don't know they need to change their config_test.yml when they add a mailer. Maybe it would help to add a short note to the documentation?

Also, the [sentence](http://symfony.com/doc/current/reference/configuration/swiftmailer.html#delivery-address) "For example, by setting this in the config_dev.yml file, you can guarantee that all emails sent during development go to a single account." where delivery_address is explained is also quite misleading. It's only true as long as there is just a single mailer.

**Comment by stof** [comment]
Feel free to send pull requests to improve the documentation. Contributions are always welcome.
