### ISSUE TITLE
Allow to display the rendered HTML contents

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/swiftmailer-bundle#114]
When displaying a real email (like a newsletter) it would be very useful if we allowed to view the rendered HTML content instead of just the HTML tags.

**Comment by stof** [comment]
A solution for this is to use an iframe in which the HTML content is rendered.
Doing it without requiring people to register a routing resource could be done using the same trick than in DoctrineBundle for the ``explain`` case, but it is kind of hacky.

**Comment by fabpot** [comment]
duplicate of #86
