### ISSUE TITLE
Mail addresses on the whitelist also send mail to the delivery_address (even though docs say it shouldn't).

### ISSUE THREAD

**Issue by msteltenpool** [symfony/swiftmailer-bundle#117]
Created the issue here, because the claim on how this should work comes from the symfony docs: http://symfony.com/doc/current/reference/configuration/swiftmailer.html#delivery-whitelist

In it, it states the following: 
"If set, emails matching any of these patterns will be delivered like normal, instead of being sent to delivery_address.". 

*config.yml*
```yml
swiftmailer:
    delivery_address: test@testing.com
    delivery_whitelist:
        - "/^error@testing.com$/"
```
Sending an e-mail to error@testing.com results in a single email being send to test@testing.com as well as error@testing.com. Due to the class Swift_Plugins_RedirectingPlugin, which takes as argument a recipient (delivery_address), and a whitelist (delivery_whitelist). If the address is whitelisted, it will add it as a To header. At the end of function the recipient (delivery_address) is added as well

```php
foreach ((array) $this->_recipient as $recipient) {
    if (!array_key_exists($recipient, $to)) {
        $message->addTo($recipient);
    }
}
```

If it's hacky for Swiftmailer bundle to fix this (could do its own whitelisting and change the recipient it sends to Swift_Plugins_RedirectingPlugin), then maybe swiftmailer/swiftmailer could add a config parameter to toggle this behaviour. Or perhaps I have overlooked something, but it seems basic enough.

**Comment by stof** [comment]
The ``delivery_whitelist`` is passed directly to the RedirectingPlugin as its whitelist. The bundle does not implement any feature for that (and it won't). It just configures the swiftmailer plugin.

If you don't like the behavior of the swiftmailer plugin, please open an issue on swiftmailer itself.

**Comment by msteltenpool** [comment]
My issue is mostly about clarity, these docs (http://symfony.com/doc/current/reference/configuration/swiftmailer.html#delivery-whitelist) are for this bundle are they not?

**Comment by stof** [comment]
Well, if the documentation on symfony.com does not match the actual behavior of the Swiftmailer plugin (or it is not clear enough), please open an issue on the symfony-docs repo asking to update the doc (or send a PR to update it).

**Comment by msteltenpool** [comment]
Thanks for the redirect. I'll close this.
