### ISSUE TITLE
Emails not sending from commands using memory spooling

### ISSUE THREAD

**Issue by mbates** [symfony/swiftmailer-bundle#127]
I'm using Symfony 2.7.3 and Swiftmailer 5.4.1 and according to the documentation (and from PR #64) these versions should automatically handle emails when memory spooling is used.

Emails are sending okay in controllers, so the config is setup correctly.

I've tried sending with the standard email code

```
$container = $this->getContainer();
$mailer = $container->get('mailer');

...

$email = \Swift_Message::newInstance()
    ->setSubject('New Email')
    ->setFrom('noreply@mydomain.com')
    ->setTo($recipients)
    ->setBody($message);
$mailer->send($email);
```

I also tried with the manual flush code at the end of the command

```
$spool = $mailer->getTransport()->getSpool();
$transport = $container->get('swiftmailer.transport.real');
$spool->flushQueue($transport);
```

Neither of these worked. (I've also checked that $recipients and $message are valid)

**Comment by mbates** [comment]
I've done some more digging and have found that when using memory spooling, flushQueue() is called from vendor/swiftmailer/swiftmailer/lib/classes/Swift/MemorySpool.php

It is calling this when the command ends, so I definitely do not need the code to manually flush the queue.

To see what was going on I edited the flushQueue() function and did a var_dump on the $transport variable. I see that it is using the null transport Swift_Transport_NullTransport to send the emails, which should only be used if disable_delivery is set on the config (or if the transport is set to null in the config)

The problem appears to be coming from this line

swiftmailer-bundle/EventListener/EmailSenderListener.php


    $spool->flushQueue($this->container->get(sprintf('swiftmailer.mailer.%s.transport.real', $name)));

I checked $name and it is "default"

I only have one mailer setup in my config

    swiftmailer:
        transport:      %mailer_transport%
        host:           %mailer_host%
        username:       %mailer_user%
        password:       %mailer_password%
        spool:          { type: memory }
        port:           %mailer_port%
        encryption:     %mailer_encryption%
        sender_address: %mailer_sender_address%

which is pulling the values from parameters.yml

    mailer_transport: sendmail
    mailer_host: smtp.sendgrid.net
    mailer_user: [USERNAME]
    mailer_password: [PASSWORD]
    mailer_port: 465
    mailer_encryption: ssl
    mailer_sender_address: noreply@mydomain.com

I also checked what I get from this line, in the same class

    $mailer = $this->container->get(sprintf('swiftmailer.mailer.%s', $name));

I've attached the file, but I'm not sure it helps much

[debug.txt](https://github.com/symfony/swiftmailer-bundle/files/74435/debug.txt)

**Comment by jsor** [comment]
Im experiencing the same bug. The bug was introduced in v2.3.10, v2.3.9 works. So my guessing is, that it has something to do with #121.

**Comment by xabbuh** [comment]
2.3.11 doesn't work either?

**Comment by jsor** [comment]
After digging deeper i think i found the problem. In my case i had  the following yml configs:

parameters.yml
```yaml
parameters:
    mailer_delivery_address: ~
```

config.yml
```yaml
imports:
    - { resource: parameters.yml }
swiftmailer:
    delivery_address: "%mailer_delivery_address%"
```

So, `delivery_address` ends as an empty string here, not as `null`: https://github.com/symfony/swiftmailer-bundle/blob/master/DependencyInjection/Configuration.php#L95

Maybe that check should something like:
```php
return array_key_exists('delivery_address', $v) && '' === (string) $v['delivery_address'];
```
That would include empty strings, `null` and `false`.

**Comment by danieldumbrava** [comment]
We also have this issue with 2.3 and Symfony 2.7.4. Our temporary solution is not that great for now, but at least it works:

Basically in a command this does not work:

```
$mailer = $this->getContainer()->get('mailer');
...
$mailer->send($message);
```

This does:

```
$transport = $this->getContainer()->get('swiftmailer.transport.real');
...
$mailer = \Swift_Mailer::newInstance($transport);
$mailer->send($message);
```

**Comment by stof** [comment]
> So, delivery_address ends as an empty string here, not as null

That's really weird. ``~`` is ``null`` in YAML

**Comment by Yopai** [comment]
Hi, 
Got the same issue on Symfony 3.2.9, with default parameters (spool set to memory).

The workaround given by @danieldumbrava is working.

**Comment by moralesfelipe** [comment]
In my case, I cannot use passwords with Ñó or similar

**Comment by kasparsj** [comment]
Hi,

We are haveing the same issue in our ExceptionController. Messages are not being set, while they are from normal controllers and even commands.

When debugging I found our that the message is being queued via MemorySpool::queueMessage, but when MemorySpool::flushQueue is called, the queued message is not there (count($this->messages) == 0).

@danieldumbrava workaround works.

Symfony v2.7.29, swiftMailer 5.4.8 and symfony/swiftmailer-bundle 2.6.2, with spool set to memory

**Comment by julienfastre** [comment]
I experienced the same issue, the workaround works.

`symfony/symfony                          v3.3.12`

**Comment by weaverryan** [comment]
For people that have issues, do you have $kernel->terminate() in your front controller? I believe that’s where the message queues are fired.

**Comment by ureimers** [comment]
@weaverryan That's correct. `\Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener` attaches itself to `KernelEvents::TERMINATE` or (when run from the console) `ConsoleEvents::TERMINATE`. Its `onTerminate` method actually uses the mailer's `transport.real` transport. So as long as your Web/CLI-Application's Kernel shuts down gracefully the emails are send.

If you're sending from a custom Plain-old-PHP-Script where you manually boot Symfony you can easily call the Listener's ´onTerminate` method yourself by calling something like `(new \Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener($container, $container->get('logger')))->onTerminate();`.

**Comment by niccolomineo** [comment]
I am working on an old 2.0 installation and can't get email to be sent in a command. This is what I am doing:

```
        $mailer = $container->get('mailer');
        $message = \Swift_Message::newInstance() (setting a bunch of things, too) 
        $mailer->send($message)
```

I tried also the following but to no avail:

```
        $transport = $container->get('swiftmailer.transport.real');
        $mailer = \Swift_Mailer::newInstance($transport);
        $message = \Swift_Message::newInstance() (setting a bunch of things, too) 
        $mailer->send($message)

```

In the latter case, I get:
`You have requested a non-existent service "swiftmailer.transport.real"`
