### ISSUE TITLE
regression in 2.3.10 (symfony 2.8.2)

### ISSUE THREAD

**Issue by craigh** [symfony/swiftmailer-bundle#129]
Apparently a regression in 2.3.10 from 2.3.9

now getting this error 

> [RuntimeException]                                                                 
  An error occurred when executing the "'cache:clear --no-warmup'" command:          

    [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]    
    Unrecognized option "delivery_address" under "swiftmailer.mailers.default"    

refs https://github.com/zikula/core/issues/2740

@fabpot

**Comment by craigh** [comment]
our swiftmailer config begins as:

> swiftmailer:
    transport: mail
    username: ''
    password: ''
    host: 'localhost'
    port: 25
    encryption: null
    auth_mode: null
    delivery_address: null
    disable_delivery: false

and is later overwritten during install. this problem was not present in 2.3.9

**Comment by xabbuh** [comment]
probably related to #121

**Comment by fabpot** [comment]
@jorns Can you have a look at this issue?

**Comment by tgabi333** [comment]
i found the problem, the exception raised when delivery_address is set to null

```
swiftmailer:
    delivery_address: ~
```

**Comment by craigh** [comment]
yes @tgabi333 but this was previously allowed and now is not and therefore a regression.

**Comment by tgabi333** [comment]
@craigh thank you! In this situation isn't it a BC break?  Another problem is that the error message is not related to the actual problem.

**Comment by craigh** [comment]
well I cannot say for sure, the original author (@jorns) needs to answer, but it appears that the config stopped accepting `delivery_address` as a key and now expects `delivery_addresses`. and yes, this is a BC break (that's the definition of regression).

**Comment by stof** [comment]
I'm working on it. The BC layer does not take care of ``null`` (as the BC currently comes from the XML handling)

**Comment by stof** [comment]
@craigh please try https://github.com/symfony/swiftmailer-bundle/pull/130

**Comment by craigh** [comment]
I cannot for several hours. I will get back to you in a day or so.

**Comment by tgabi333** [comment]
@stof it worked for me, thanks

**Comment by craigh** [comment]
@Guite can you try this for us?

**Comment by Guite** [comment]
Here is what I did:
1. Cloned the repository
2. Changed version of SwiftMailer in composer file from `2.3.9` back to `2.3.*`
3. Executed composer install -> broke due to the problem
4. Applied the path from #130 
4. Executed composer install again -> went through this time
5. Opened the installation page -> worked fine

**Comment by craigh** [comment]
sounds like it is a fix for us then.

**Comment by fabpot** [comment]
2.3.11 is out with the fix

**Comment by craigh** [comment]
thanks all!
