### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/swiftmailer-bundle#131]
This repository has no LICENSE file.

The symfony/symfony repository has this file: https://github.com/symfony/symfony/blob/master/LICENSE

**Comment by alexislefebvre** [comment]
Does the beginning year in the `LICENSE` file should be 2010, the date of the first commit https://github.com/symfony/swiftmailer-bundle/commit/947708c05aeb82f9a019bbfa1f2e4e405e396935?

**Comment by fabpot** [comment]
LICENSE is here: https://github.com/symfony/swiftmailer-bundle/blob/master/Resources/meta/LICENSE

**Comment by alexislefebvre** [comment]
Oops, I didn't see it. Thanks.
