### ISSUE TITLE
MessageDataCollector not correctly checking if Swift_Mailer is initialized

### ISSUE THREAD

**Issue by echochamber** [symfony/swiftmailer-bundle#139]
Before I opened a PR to actually fix this I thought I would ask if there was some obscure reason why we are checking if swiftmailer has been initialized differently in the EmailSenderListener and the MessageDataCollector:

[MessageDataCollector.php](https://github.com/symfony/swiftmailer-bundle/blob/master/DataCollector/MessageDataCollector.php#L54)

```php
// MessageDataCollector.php
// ...
    public function collect(Request $request, Response $response, \Exception $exception = null)
    {
        $this->data = array(
            'mailer' => array(),
            'messageCount' => 0,
            'defaultMailer' => '',
        );
        // only collect when Swiftmailer has already been initialized
        if (class_exists('Swift_Mailer', false)) {
```

[EmailSenderListener.php](https://github.com/symfony/swiftmailer-bundle/blob/master/EventListener/EmailSenderListener.php#L53)

```php
// EmailSenderListener.php
// ...
    public function onTerminate()
    {
        if (!$this->container->has('mailer')) {
            return;
        }
        $mailers = array_keys($this->container->getParameter('swiftmailer.mailers'));
        foreach ($mailers as $name) {
            if ($this->container instanceof IntrospectableContainerInterface ? $this->container->initialized(sprintf('swiftmailer.mailer.%s', $name)) : true) {

```

**How I encountered this:** I ran into the following issue when writing some behat tests that involved checking the profiler for an email. In order to get the MessageDataCollector to actually do the collection I had to add `require_once (__DIR__ . '/../../../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php');` to my test step definition just so that this line `if (class_exists('Swift_Mailer', false)) {` in `MessageDataCollector.php` would return true.

**My error**: Calling $collector->getMessages() `resulted in the following exception
```
LogicException' with message 'Missing default data in Symfony\Bundle\SwiftmailerBundle\DataCollector\MessageDataCollector' in vendor/symfony/swiftmailer-bundle/DataCollector/MessageDataCollector.php:99
```

**Proposed Solutions**:

* **Solution 1**: In **MessageDataCollector.php**, replace `if (class_exists('Swift_Mailer', false)) {` with `if ($this->container instanceof IntrospectableContainerInterface ? $this->container->initialized(sprintf('swiftmailer.mailer.%s', $name)) : true) {`
    * This would change the behavior as it would mean that there would be cases where data would be collected where it previously wouldn't have: Only in Symfony versions < ~3.0 when swift mailer isn't initialized and the container isn't implementing IntrospectableContainerInterface.
    * This change in behavior could be avoided if instead the if statement was rewritten like this: `if ( ($this->container instanceof IntrospectableContainerInterface && $this->container->initialized(sprintf('swiftmailer.mailer.%s', $name))) || class_exists('Swift_Mailer', false)) {`
    * This would trigger collection if **either** the container says swiftmailer is iniitalized, or by the previous criteria of simply checking if the class_exists.
* **Solution 2**: In **MessageDataCollector.php**, get rid of the **false** second parameter in  `if (class_exists('Swift_Mailer', false)) {` so it would become `(class_exists('Swift_Mailer')) {`
    * This one I'm not sure if it would have any repercussions or side effects. As far as I can tell if Swift_Mailer it hasn't for me, but I don't know what the criteria is for when Swift_Mailer is actually require_once() as opposed to just autoloaded

**Comment by echochamber** [comment]
@stof I've noticed that the issues here don't seem to get many responses. I think since this isn't shipped under the symfony/symfony main distribution I am supposed to report this error here instead of on the main symfony repository. Is this correct?

Also I am happy to submit a PR for any of my suggested fixes if anybody can verify I am not mistaken in my assessment.

**Comment by MetalArend** [comment]
Keep in mind that the IntrospectableContainerInterface is deprecated since 2.8: https://github.com/symfony/dependency-injection/blob/master/CHANGELOG.md#280

**Comment by fabpot** [comment]
We are now using method_exists as the interface does not exist anymore in 3.0.

**Comment by echochamber** [comment]
ty @fabpot

**Comment by jcornide** [comment]
Hi, 
I ran exactly on the same problem as @echochamber, how did you work around this?

**Comment by echochamber** [comment]
@jcornide I ended up manually editing the bundle code in the vendor dir. (see solution 1 in my initial post in this thread). It ended up not being important though so I didn't follow up. Since `IntrospectableContainerInterface` doesn't exist anymore (to the best of my knowledge, not doing much Symfony work recently) I don't think it will work. But solution 2 should still work.
