### ISSUE TITLE
Regression: delivery_address in 2.3.11

### ISSUE THREAD

**Issue by Padam87** [symfony/swiftmailer-bundle#140]
After a composer update, I got this error:

Warning: Illegal offset type 
https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Mime/SimpleMessage.php#L297

The `$address` variable is an array, like `array(0 => "my.address@example.com")`

I've reverted to 2.3.9, problem not present. I assume it has something to do with the recent changes allowing multiple addresses.

**Comment by xabbuh** [comment]
Maybe related to #132. Can you check if #136 fixes your issue?

**Comment by slaci** [comment]
I encountered this problem too, and for the record: it is not fixed by the linked PR. It is a bug in swiftmailer itself, so the solution is to upgrade the swiftmailer lib to >5.1.
Under version 5.1 the redirection plugin cannot handle arrays.
