### ISSUE TITLE
Incorporate functionality of SwiftmailerEventsBundle

### ISSUE THREAD

**Issue by PatchRanger** [symfony/swiftmailer-bundle#142]
## Description

There is a very useful bundle related to Symfony2 Swiftmailer integration called SwiftmailerEventsBundle: https://github.com/TDMobility/SwiftmailerEventsBundle .
There are two primary features added by the bundle. Adding additional data to the message object, and triggering events on mailer send as well as imap transport send.
Here is the detailed use case: https://blog.anodetome.com/2013/07/12/dynamic-smtp-settings-per-message-in-symfony2/ .
The problem is that it is not much maintained.
I guess, it is definitely worth merging this bundle into SwiftmailerBundle.

**Comment by sstok** [comment]
👎 The Swiftmailer already has an event system that you can use for such use-cases, and adding transport information to a message? That sounds like a terrible idea, the message is about the message, it should not know about it's sending mechanism (and it's configuration).

**Comment by PatchRanger** [comment]
@sstok Personally I agree, there should be a separation of concerns. And I would be against of attaching transport configuration to message itself. But there is a use-case, described in the aforementioned blog post (it's not mine): how would you solve the issue of changing SMTP-transport according to From header of the message? Otherwise the message would be (correctly) considered as spam.
So it's not a fake problem - it's a real problem. It's not an additional functionality - it is a correction of misbehavior. That's why in my view SwiftmailerEventsBundle should be incorporated.

**Comment by stof** [comment]
IMO, the right solution for the use case described in the blog post is not to attach transport settings to the message, but to write a custom transport implementation which would read the From header and change the underlying transport being used (the custom transport would use delegation to call a real transport internally). It is much cleaner than adding data in the message for that.

And being able to change the transport on a per-message basis **is** a new feature, not a bugfix.
