### ISSUE TITLE
Problems with newline in body of messages

### ISSUE THREAD

**Issue by Nexotap** [symfony/swiftmailer-bundle#150]
I'm not sure if I'm at the right place here, neither if it's a real problem or just me having a bad system configuration.

I found out about this problem while using FOSUserBundle, but I dont think this matters. 
Please forgive me, I dont even know excactly how to describe it.

While having a look at the function sendMessage(...) in TwigSwiftMailer.php there the variable $textBody.

The string in this variable seems to be somehow  single quoted and therefore in the generated email \n wont do a newline. It just prints \n. 

What I did, after defining the variable, is the following:

$textBody = str_replace('\n', "\n", $textBody);

This magically converts that single quoted string into a double quoted string and the resulting email gets outputtedd correctly.

I am sorry again if I am at the wrong place. I haven't found anything related to this while searching on the internet.

Can someone please enlighten me?

**Comment by Nexotap** [comment]
More than 2 month passed. Now I'm wondering am I really the only one encountering this problem?
Or am I maybe the only one trying weird  things which noone else would do?

Is it maybe a setting in PHP? Or does it comes from the os?

**Comment by xabbuh** [comment]
@Nexotap There is no concept of a single-quoted or double-quoted string in PHP. Single and double quotes only influence how character of this string are interpreted when the string is built. So this looks like something going wrong before. Where is the contents of the `$textBody` variable coming from? Do you dynamically create the message body?

**Comment by Nexotap** [comment]
As said, I'm not sure if this issue belongs here or maybe  to FOSUserBundle . 
I haven't done anything special. Please see the mentioned function, which can be found at
friendsofsymfony/user-bundle/TwigSwiftMailer.php

```
protected function sendMessage($templateName, $context, $fromEmail, $toEmail)
    {
        $context = $this->twig->mergeGlobals($context);
        $template = $this->twig->loadTemplate($templateName);
        $subject = $template->renderBlock('subject', $context);
        $textBody = $template->renderBlock('body_text', $context);
        $htmlBody = $template->renderBlock('body_html', $context);

        /*
         * convert single quoted string to double quoted
         */
        $textBody = str_replace('\n', "\n", $textBody);

        $message = \Swift_Message::newInstance()
            ->setSubject($subject)
            ->setFrom($fromEmail)
            ->setTo($toEmail);

        if (!empty($htmlBody)) {
            $message->setBody($htmlBody, 'text/html')
                ->addPart($textBody, 'text/plain');
        } else {
            $message->setBody($textBody);
        }

        $this->mailer->send($message);
    }

```
If I don't put this str_replace thing,  it behaves as I mentioned in my first post. The whole newline stuff doesn't work and it prints \n instead of newline. I'm using a vanilla FOSUserBundle. I haven't even changed anything on the mail templates.

I don't know what else I can say about it. I can live with it, but it looks strange to me.

**Comment by xabbuh** [comment]
Can you upload a fork of the Symfony Standard Edition that makes your issue reproducable?

**Comment by Nexotap** [comment]
I feel ashamed now. Tried to reproduce this issue without success.
Even removed that line of code in sendMessage from the project where I encountered that problem and the _\n_ is still interpreted correctly.
I'm basically out of words.

Thank you anyway for your attention @xabbuh .
