### ISSUE TITLE
Updating composer.json to fix CVE 2016 10074 ?

### ISSUE THREAD

**Issue by thomandre** [symfony/swiftmailer-bundle#154]
Hello,

I'd like to know why the composer.json is not yet updated to support the last version of swiftmailer/swiftmailer.
Should I make a pull request?

Happy new year and thanks :)

Thomas

**Comment by lyrixx** [comment]
Hello.

I'm not sure to understand why you said that. This package require ` "swiftmailer/swiftmailer": ">=4.2.0,~5.0",` And the last release of swiftmailer is [v5.4.5](https://github.com/swiftmailer/swiftmailer/releases).
So this bundle should be compatible with the last version of swiftmailer.

**Comment by stof** [comment]
I think this is a misunderstanding of the difference between a composer.json and a composer.lock file...

I'm closing this as there is strictly nothing to do in this bundle (as I already said in #153).
