### ISSUE TITLE
The disable_delivery flag is broken in 2.5.0

### ISSUE THREAD

**Issue by viccherubini** [symfony/swiftmailer-bundle#160]
The `disable_delivery` flag is not respected in version 2.5.0. It works fine in 2.4.2, but when upgrading to 2.5.0, emails in my test cases are being sent out. Running Symfony 3.2.4.

Setting the `swiftmailer.transport` value to `'null'` appears to have fixed this, but I don't see it documented anywhere that it has to be both `'null'` and `disable_delivery: true`.

**Comment by xabbuh** [comment]
You shouldn't have to use both. Can you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by jean-gui** [comment]
Same issue here. How to reproduce:
- create a brand new project
- add `disable_delivery: true` under the swiftmailer section of app/config/config.yml
- add the following code to AppBundle/Controller/DefaultController, IndexAction():
```php
$message = \Swift_Message::newInstance()
            ->setSubject('Hello Email')
            ->setFrom('test@example.org')
            ->setTo('test@example.org')
            ->setBody('test');

        $this->get('mailer')->send($message);
```
- check out mail server logs (/var/log/mail.log in my case): you'll see that it attempted to deliver an email

**Comment by viccherubini** [comment]
Thanks for that, @jean-gui. I noticed it because my test suite started sending out actual emails.

**Comment by jean-gui** [comment]
It's also worth noting that `php bin/console debug:swiftmailer` replies what's expected (Delivery: NO).

**Comment by fabpot** [comment]
Probably due to the latest changes done by @mykiwi.

**Comment by HeahDude** [comment]
https://github.com/symfony/swiftmailer-bundle/pull/161 should fix it. Can someone please confirm?
