### ISSUE TITLE
2.6.1 still pulling in swiftmailer 6

### ISSUE THREAD

**Issue by delamart** [symfony/swiftmailer-bundle#174]
I believe the dependency is wrong:
`symfony/swiftmailer-bundle  v2.6.1  requires  swiftmailer/swiftmailer (>=4.2.0|~5.0) `
The `>=4.2.0` still includes swiftmailer 6.

**Comment by fabpot** [comment]
Indeed, just released 2.6.2 to fix this issue.

**Comment by delamart** [comment]
Thanks, it reverted to 5.4.8 on composer update.
