### ISSUE TITLE
Question only: What is the release strategy of Swiftmailer Bundle

### ISSUE THREAD

**Issue by lbayerl** [symfony/swiftmailer-bundle#176]
As a Symfony user I love to use Swiftmailer Bundle, but I don't fully understand the release strategy.

Looking at the latest releases there have been four 2.x releases while a 3.0 is already existing: 2.3.x, 2.4.x, 2.5.x.

They do not seem to match with Symfony framework release numbers but I cannot find anywhere some information why there are so many maintained parallel streams of this bundle and when/whether it makes sense to upgrade etc.

Do I miss some information here or was I simply to blind to see?

**Comment by stof** [comment]
so many parallel streams of this bundle ? I don't understand what your mean. There is no 2.3.x, 2.4.x or 2.5.x branches for this bundle

**Comment by lbayerl** [comment]
According to the [releases tab](https://github.com/symfony/swiftmailer-bundle/releases) here on Github the following tags are the 'released' versions of this bundle within the last 10 days: 2.5.5, 2.3.12, 2.4.3, 2.6.2, 3.0.1, 3.0.0, 2.6.1, 2.6.0 - that's what I mean and don't comprehend.
