### ISSUE TITLE
Sending errors emails by monolog broken when memory spool enabled

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/swiftmailer-bundle#182]
This is to be fixed in symfony at the same time (doc change): https://github.com/symfony/symfony/issues/23334

Broken in 7cc472f19ad6259b3ffa09016d03b23d0037868d

To have the benefit of above fix, I propose to add some configuration/spoolType which does not send email on error.

**Comment by fabpot** [comment]
Closing as Swiftmailer is not maintained anymore and in any case, the spool feature of Swiftmailer was really weak. Migrating to Symfony Mailer would give a way better way to send emails async.
