### ISSUE TITLE
Should the master and 3.x branches depend on PHP >=7.0.0 ?

### ISSUE THREAD

**Issue by vamsiikrishna** [symfony/swiftmailer-bundle#183]
Hi !
Since [```symfony/swiftmailer-bundle```](https://github.com/symfony/swiftmailer-bundle/) depends on [```swiftmailer/swiftmailer```](https://packagist.org/packages/swiftmailer/swiftmailer#v6.0.1)
  version ```6.0.1``` ,  should the PHP version required in composer.json of this library be set to ``` >=7.0.0``` instead of ```>=5.3.2```.

Thanks

**Comment by fabpot** [comment]
Done
