### ISSUE TITLE
v2.6.2: Listening to ConsoleEvents::EXCEPTION throws error in Symfony 3.3

### ISSUE THREAD

**Issue by Batch1211** [symfony/swiftmailer-bundle#184]
As many people still use v.2.6.2 becasue >v3 requires PHP7, we should fix an error that is thrown once the user updates to Symfony 3.3 or higher.

The problem is, that the EventListener/EmailSenderListener class registers an event called ConsoleEvents::EXCEPTION, which from Symfony 3.3 and higher is deprecated and throws an error, when found. 

In my case, this caused functional tests for the PHP 5.6 environment to fail.

**Comment by ktrzos** [comment]
+1

**Comment by nmeirik** [comment]
+1

**Comment by chalasr** [comment]
https://github.com/symfony/swiftmailer-bundle/pull/179 needs to be back ported.

**Comment by fabpot** [comment]
fixed in 2.6.3.
