### ISSUE TITLE
Allow encryption and auth_mode to be empty

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/swiftmailer-bundle#186]
In Symfony 4, the mailer will be configured with this env var:

```ini
MAILER_URL=smtp://localhost:25?encryption=&auth_mode=
```

This causes some bugs because `encryption` and `auth_mode` can't be empty:

```
  [InvalidArgumentException]
  The  encryption is not supported

  [InvalidArgumentException]
  The  authentication mode is not supported
```

@yann-eugone investigated the issue and found that:

> Regarding of Symfony\Bundle\SwiftmailerBundle\DependencyInjection\SwiftmailerTransportFactory I found that the URL query part is parsed with parse_str and the values are added one after the other without trying to convert it.
>
> We can solve it by modifying the resolveOptions method of SwiftmailerTransportFactory to replace empty string with null

**Comment by kironet** [comment]
@javiereguiluz Hi, sorry but how can I specify smtp username and password?
