### ISSUE TITLE
Deprecated use of service

### ISSUE THREAD

**Issue by garak** [symfony/swiftmailer-bundle#191]
Using swiftmailer-bundle v3.0.4 and symfony 3.3, I'm getting the following deprecation notices:

* Checking for the existence of the "mailer" private service is deprecated since Symfony 3.2 and won't be supported anymore in Symfony 4.0
* Requesting the "swiftmailer.mailer.default.transport.real" private service is deprecated since Symfony 3.2 and won't be supported anymore in Symfony 4.0
* Checking for the existence of the "swiftmailer.mailer.default.plugin.messagelogger" private service is deprecated since Symfony 3.2 and won't be supported anymore in Symfony 4.0
* Requesting the "swiftmailer.mailer.default.plugin.messagelogger" private service is deprecated since Symfony 3.2 and won't be supported anymore in Symfony 4.0

**Comment by stof** [comment]
Looks like you are using the dev version of the symfony/dependency-injection component, as `mailer`becoming private looks related to changes belonging to Symfony 3.4, not to 3.3

**Comment by garak** [comment]
Well, I'm indeed using Flex, with a mix of 3.3 and 3.4@dev (debug toolbar reporting 3.3.9 anyway).

**Comment by stof** [comment]
Well, then these messages are expected. We need to make a few changes in SwiftmailerBundle to account for changes merged in symfony/dependency-injection yesterday, and they have not been done yet.

**Comment by javiereguiluz** [comment]
Closing as fixed by #200 and #203.
