### ISSUE TITLE
Version 3.1.1 is not compatible with symfony ^3.0

### ISSUE THREAD

**Issue by wachterjohannes** [symfony/swiftmailer-bundle#198]
The tagged version `3.1.1` of this bundle is not compatible with symfony `^3.0` because of this condition: `"symfony/dependency-injection": "~2.7|~3.4|~4.0"`

This seems to be only compatible with not stable 3.4 release of symfony

See my composer update screenshot:

![image](https://user-images.githubusercontent.com/1464615/31652498-9f21a06a-b31f-11e7-88f1-1c23eb2d23e5.png)

**Comment by stof** [comment]
hmm, changing the DI requirement was a mistake I think. As it is compatible with 2.7, there is no reason for it to be incompatible with 3.3.

**Comment by cerilo** [comment]
Save problem for me

**Comment by fabpot** [comment]
It was done in 5934f84 by @ro0NL.

**Comment by xabbuh** [comment]
fixed in #199
