### ISSUE TITLE
Allow to specify a command option for sendmail transport

### ISSUE THREAD

**Issue by Gregoire-M** [symfony/swiftmailer-bundle#20]
The sendmail transport uses a UNIX command to send mails. The default command is `/usr/sbin/sendmail -bs`. There is currently no way to modify it through the bundle configuration.

**Comment by tobiasmuehl** [comment]
Has this been added yet?

**Comment by mhdev90** [comment]
Look at this pull request: https://github.com/symfony/swiftmailer-bundle/pull/185.

**Comment by kojiDev** [comment]
The issue is obsolete. Would someone come along and close it?
