### ISSUE TITLE
Call to a member function setPublic() on null

### ISSUE THREAD

**Issue by iBet7o** [symfony/swiftmailer-bundle#201]
Update my dependencies and show me the following error.

![swiftmailer-error](https://user-images.githubusercontent.com/590235/31747003-0aeccee4-b430-11e7-86d1-bba54cdfd260.png)

**Comment by pppdns** [comment]
same here, updated from 2.6.3 to 2.6.5 and this happened

**Comment by fabpot** [comment]
Which version of Symfony do you have?

**Comment by fabpot** [comment]
ok, I know why. Patch soon.

**Comment by fabpot** [comment]
fixed in 2.6.6.
