### ISSUE TITLE
2.6.4 and above use ::class, making them incompatible with PHP <5.5

### ISSUE THREAD

**Issue by mogzol** [symfony/swiftmailer-bundle#202]
As of v2.6.4, the file `DependencyInjection/SwiftmailerExtension.php` uses `::class`, as you can see here:

https://github.com/symfony/swiftmailer-bundle/blob/9cea79f70bf22b7a1623e93342e946ca5d9bcdd7/DependencyInjection/SwiftmailerExtension.php#L234

This makes the bundle incompatible with PHP <5.5. Despite this, the composer.json file claims that it is still compatible with PHP 5.3.2 and above.

**Comment by fabpot** [comment]
Can you submit a pull request to fix that?
