### ISSUE TITLE
Updates required for symfony 3.4+

### ISSUE THREAD

**Issue by cordoval** [symfony/swiftmailer-bundle#215]
User Deprecated: The "swiftmailer.mailer.default.plugin.messagelogger" service is private, checking for its existence is deprecated since Symfony 3.2 and will fail in 4.0.

**Comment by yceruto** [comment]
It seems ready in the latest version:
https://github.com/symfony/swiftmailer-bundle/blob/9728097df87e76e2db71fc41fd7d211c06daea3e/DependencyInjection/SwiftmailerExtension.php#L365-L366
