### ISSUE TITLE
Integrate mailer_url for tierce library

### ISSUE THREAD

**Issue by Nightbr** [symfony/swiftmailer-bundle#217]
Hello, 

I would like to handle MAILER_URL with Mailjet library such as `mailjet://apikey:apisecret@api.mailjet.com/v3`. 

I looked into https://github.com/symfony/swiftmailer-bundle/blob/master/DependencyInjection/SwiftmailerTransportFactory.php and it seems that we only can use `smtp`, `sendmail`,  `gmail` or `null`.

My question is : is it a way to handle custom url bind on custom SwiftMailer transport in swiftmailer-bundle or we have to handle this into our bundle and use classic configuration `transport: mailjet`?

Thanks in advance!

Related: https://github.com/mailjet/mailjetBundle/issues/7

**Comment by fabpot** [comment]
This has been implemented in Symfony Mailer.
