### ISSUE TITLE
[DX] Display HTML preview for e-mails

### ISSUE THREAD

**Issue by kiler129** [symfony/swiftmailer-bundle#222]
Testing e-mail with developer profiler is awesome until you realize your frontend developers wrote 2000 lines of HTML for an order confirmation ;-)

Currently the console for with e-mails sent looks like that:
<img width="1217" alt="screenshot 2018-01-25 03 13 43" src="https://user-images.githubusercontent.com/1227834/35380538-2ad5d826-017f-11e8-88f5-8417f4a1ea19.png">

It's nice, but if it contains HTML preview of the message it will be even better:
<img width="1214" alt="screenshot 2018-01-25 03 23 28" src="https://user-images.githubusercontent.com/1227834/35380564-4139ce9c-017f-11e8-94fa-641f37741eb4.png">

Of course the content has to be sandboxed in `<iframe>`. A slight downside of this approach is the content has to be populated using JS - I'm not aware of any way of populating `<iframe>`s without JS.

Is it a welcomed change?

**Comment by lyrixx** [comment]
I think it's a could idea ;) :+1:

**Comment by kiler129** [comment]
@lyrixx Implemented with some bells & whistles ;)
