### ISSUE TITLE
Rendered content ignores newlines in text/plain

### ISSUE THREAD

**Issue by garak** [symfony/swiftmailer-bundle#229]
The new feature introduced in #228 is great, but I think the rendered part is wrong when email is text/plain.
In such case, newlines should be converted to BRs.
Example of raw content:
```
Hello user
this is your reservation id: 12345

Thanks!
the staff
```

Expected rendered content: the same as the raw.
Current rendered content:
```
Hello user this is your reservation id: 12345 Thanks! the staff
```

**Comment by ro0NL** [comment]
Im hitting the same issue.

I use text/html as alternative mime part (body is text/plain).

I expected a) newlines b) the alternative part to be used...

**Comment by stof** [comment]
@javiereguiluz could you check this case ?
