### ISSUE TITLE
Error when rendering Mail in Profiler

### ISSUE THREAD

**Issue by Gemineye** [symfony/swiftmailer-bundle#233]
Impossible to access an attribute ("toString") on a null variable.
in vendor/symfony/swiftmailer-bundle/Resources/views/Collector/swiftmailer.html.twig (line 196)

<pre class="prewrap">{{ message.headers.get('to').toString|replace({'To:': ''}) }}</pre>

We send emails without a "to" value, only bcc. This does not work with the new template.

**Comment by javiereguiluz** [comment]
Thanks for reporting this error. We're trying to fix it in #236.
