### ISSUE TITLE
PHP version incompatibility

### ISSUE THREAD

**Issue by nicolasmoreira** [symfony/swiftmailer-bundle#241]
Hi,

This version bundle https://packagist.org/packages/symfony/swiftmailer-bundle#v3.0.3 requires **php: >=5.3.2** but also requires swiftmailer/swiftmailer: ^6.0.1 that requires **php: >=7.0.0** so we can't install swiftmailer-bundle#v3.0.3 on PHP 5 environments.

**Comment by weaverryan** [comment]
Hmmm. Indeed! We won’t change the swiftmailer version in the bundle, however.

So, we could clarify by changing the php version in this bundle, but it won’t solve your issue. For php 5, I believe you’ll need to use v2 of the bundle.

**Comment by nicolasmoreira** [comment]
Yes, i do that. Thanks!

**Comment by chalasr** [comment]
The constraint has been changed to `^7.0` in v3.0.4.
