### ISSUE TITLE
[RFC] Add SwiftMessage with twig support

### ISSUE THREAD

**Issue by Nek-** [symfony/swiftmailer-bundle#248]
I think almost everybody is using Twig to render their emails. It's probably time to makes it easier.

Usage
------

```
// Should act like the template system using in the controller
$message = (new TemplateSwiftMessage())->setTemplate('foo.html.twig');
$mailer->send($message);
```

How
-----

Inherit the `Swift_Mailer` class and `Swift_Message` class.

What do you think of this proposal?

**Comment by javiereguiluz** [comment]
See https://github.com/symfony/symfony/issues/15060

**Comment by Nek-** [comment]
I guess your addition should be here, in the swiftmailer bundle. But it looks really ok to me. Also you said it was refused by 👎 but look before, here is what I saw:
![image](https://user-images.githubusercontent.com/972456/42039326-67baec12-7aed-11e8-9c34-04d179b878d5.png)

So I guess your favorable to this kind of change ? :) (if you ask on twitter I'm pretty sure it will be a warm welcome)

**Comment by fabpot** [comment]
This has been implemented in Symfony Mailer.
