### ISSUE TITLE
Flush Memory Spool with Messenger

### ISSUE THREAD

**Issue by felipyamorim** [symfony/swiftmailer-bundle#254]
Hello, 

I tried to queue swiftmailer mails with symfony messenger, but he can't send e-mail from consumer, because the messenger command doesn't trigger event to flush memory spool.

how to get around this?

https://gist.github.com/felipyamorim/a1d75550524652966ebc20e09ff25303

**Comment by kojiDev** [comment]
If a message to be sent immediately than disable spool

**Comment by sandermarechal** [comment]
You can't disable the spool just for the message consumer. Perhaps the swiftmailer-bundle should also hook into the Messenger events to trigger sending the in-memory spool? Using the [WorkerMessageHandledEvent](https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Messenger/Event/WorkerMessageHandledEvent.php) perhaps? You'd still need to detect whether you're running as a consumer or not.

**Comment by fabpot** [comment]
You should probably move to Symfony Mailer instead.
