### ISSUE TITLE
SmtpTransportConfigurator does not use the correct request data in some cases

### ISSUE THREAD

**Issue by ampaze** [symfony/swiftmailer-bundle#257]
In my case the mailer ist injected in a Doctrine EntityListener at which point in time RequestContext::fromRequest has not yet been called.

This results in Swiftmailer using localhost for the SMPT HELO.

SmtpTransportConfigurator::configure should really only be called after the RequestContext is correctly initialized.

**Comment by fabpot** [comment]
Closing as this bundle is not maintained anymore.
