### ISSUE TITLE
Self-signed certificate in 4.1.3

### ISSUE THREAD

**Issue by Amagali** [symfony/swiftmailer-bundle#277]
Hello. I know I have to go to Stackoverflow for troubleshoot but I don't get any help there and I'm kinda desperate because I can't find any answer anywhere and don't know where to look here about what version you are talking in the issues.

https://stackoverflow.com/questions/54923629/symfony-1-4-sfmailer-configure-tls-self-signed-certificate-unable-to-find-the

Any help would be appreciated. Thank you.

**Comment by stof** [comment]
this bundle is not about Symfony 1.4 at all.

**Comment by Amagali** [comment]
Sorry! I think I mixed up github projects!
