### ISSUE TITLE
stream_socket_client(): unable to connect

### ISSUE THREAD

**Issue by louia** [symfony/swiftmailer-bundle#279]
I have this error ????
`[2019-04-11 20:09:49] php.DEBUG: Warning: stream_socket_client(): unable to connect to ssl://ssl0.ovh.net:465 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/mielleriem/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php\",\"line\":267,\"trace\":[{\"file\":\"/home/mielleriem/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php\",\"line\":58,\"function\":\"establishSocketConnection\",\"class\":\"Swift_Transport_StreamBuffer\",\"type\":\"->\"}],\"count\":1})"} []
[2019-04-11 20:09:49] app.ERROR: Exception occurred while flushing email queue: Connection could not be established with host ssl0.ovh.net [Connection refused #111] [] []`

And my swifmailer.yaml 
look like that : (this is the good credit, i try the same credit with PHPMailer on the same server)

`swiftmailer:
    transport: smtp
    host: ssl0.ovh.net
    port: 465
    auth_mode: login
    encryption: ssl
    #auth_mode: login
    username: admin@*******.fr
    password: *********
    #intercept_redirects: true
    # disable_delivery: false
    # url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }`

and my .env look like 
`MAILER_URL=null://localhost`

**Comment by xabbuh** [comment]
I am closing here as a duplicate as there already is the same issue in swiftmailer/swiftmailer#1190. Thank you for understanding.
