### ISSUE TITLE
[bug] compiler pass throws when no default_mailer configured

### ISSUE THREAD

**Issue by akomm** [symfony/swiftmailer-bundle#280]
When you do not want to define a default mailer (there are good reasons you might not want to), the [compiler pass](https://github.com/symfony/swiftmailer-bundle/blob/856c19b6989cf7431403f98161cedd6f4f5fdf1a/DependencyInjection/Compiler/RegisterPluginsPass.php#L27) throws.

This is the reason:
```php
// \Symfony\Bundle\SwiftmailerBundle\DependencyInjection\Compiler\RegisterPluginsPass:27
if (!$container->findDefinition('swiftmailer.mailer') || !$container->getParameter('swiftmailer.mailers')) {
    return;
}
```
Because `findDefinition` throws.

Note: I do not use the default mailer anywhere. Only two places with explicit injection configured to inject a non default mailer instance. Not autowired.

**Comment by akomm** [comment]
Obviously, when you accidentally attempt to use the default but no is defined, it should throw. Being able to not define default mailer when using different configuration is a good controlling feature, when you accidentally do not inject explicit the specific profile. When I am forced to define a default I will not notice the error and maybe use the wrong configuration to send emails.

**Comment by fabpot** [comment]
Closing as we won't add new features to this bundle.
