### ISSUE TITLE
`delivery_addresses` configuration only works in `dev` Environment

### ISSUE THREAD

**Issue by jonnyeom** [symfony/swiftmailer-bundle#285]
### Description
I have setup a separate environment (lets say. `stage`) and I have a `config/packages/stage/swiftmailer.yaml` file.
```yaml
swiftmailer:
    delivery_addresses: ['catcher@email.com']
```

I have `delivery_addresses` set but the email recipients are not being overridden like in the `dev` environment.

Interestingly, `delivery_addresses` setting only work in the *dev* environment.

### Environment
* Symfony v4.2.8
* Swiftmailer v6.2.1

### Expected behavior
`delivery_addresses` configured in config/packages/{{ environment }}/swiftmailer.yml works for each environment.

### Actual behavior
`delivery_addresses` only works in `dev` environment

**Comment by mark-orion** [comment]
Same problem here. I second that 'delivery_addresses' should work in any environment it is configured for because one wants to give even a production environment a thorough check before rollout.

**Comment by dmaicher** [comment]
Actually I'm using `delivery_addresses` in my staging environment (Symfony env name `staging`) and its working perfectly fine.

Also I cannot find anything in the code that would make this feature only work for `dev`.

Can you create a small reproducer project for this?

**Comment by fabpot** [comment]
Closing as there is no feedback
