### ISSUE TITLE
send() function return 0 within Command

### ISSUE THREAD

**Issue by Ugolaf** [symfony/swiftmailer-bundle#299]
I have a problem sending my emails with Symfony. 

swiftmailer.yaml
`swiftmailer:
  default_mailer: gmail_api
  mailers:
    gmail_api:
      transport: gmail_api`

As you can see I'm not using the spooling.

My emails are sent from Controller but not from Command.

From Controller, send() return 1 and I receive the email.

\Swift_Plugins_Loggers_ArrayLogger give me:
++ Starting Swift_Transport_EsmtpTransport
...
<< 250 OK

From Command, send() return 0 and I don't receive the email.

\Swift_Plugins_Loggers_ArrayLogger give me:
++ Starting App\Service\Email\GmailApiTransport
++ App\Service\Email\GmailApiTransport started

Why it's not starting with Swift_Transport_EsmtpTransport within Command?

**Comment by fabpot** [comment]
Closing as we don't use Github for support
