### ISSUE TITLE
EmailSenderListener adds significant overhead

### ISSUE THREAD

**Issue by schmittjoh** [symfony/swiftmailer-bundle#3]
see symfony/symfony#3396

**Comment by MetalArend** [comment]
This is a very old issue, but as the IntrospectableContainerInterface was removed from Symfony 3.0, the overhead that was mentioned here seems to be back. It seems removing the check for the IntrospectableContainerInterface implemented in symfony/symfony#3557 does the trick - if you are using Symfony 3.0.

**Comment by sstok** [comment]
@MetalArend The IntrospectableContainerInterface is merged in the the ContainerInterface, the EmailSenderListener needs to be updated for this.

A method_exists() for `initialized` should do the trick. Feel free to open a pull-request.
