### ISSUE TITLE
EmailListener not processing result of sent emails

### ISSUE THREAD

**Issue by poolerMF** [symfony/swiftmailer-bundle#301]
EmailListener is calling $spool->flushQueue($this->container->get(sprintf('swiftmailer.mailer.%s.transport.real', $name)));

function flushQueue is returning number of sent emails
function flushQueue can have second parameter $failedRecipients

- those two informations need to be processed and exception returned if needed

how to simulate it ?
just pass wrong credentials into MAILER_URL .... emails will not be sent, there will be no information about that, no exception

**Comment by fabpot** [comment]
Fixed by #313
