### ISSUE TITLE
Logging enabled creates memory leaks in long-living apps/commands

### ISSUE THREAD

**Issue by proArtex** [symfony/swiftmailer-bundle#303]
As per doc, "logging" is set to %kernel.debug% by default, which creates memory leaks in consumers and long-living commands with debug enabled. The leakage itself is in MessageLogger plugin that only appends messages. The details are [here](https://github.com/swiftmailer/swiftmailer/issues/1294). I wonder if there is any solution already? We could find a way to distinguish a long living process/command and set "logging" from a variable.

**Comment by fabpot** [comment]
Closing as the issue is in Swiftmailer itself.
