### ISSUE TITLE
Missing `swiftmailer.mailer.smtp.transport.smtp.host` if using environment variables and delivery is not disabled.

### ISSUE THREAD

**Issue by oleg-andreyev** [symfony/swiftmailer-bundle#307]
Some parameters are missing in container when using environment variables and delivery  is not disabled.

Locally we're using local smtp and on production we're running external smtp but some of services (in vendor) are relaying on `swiftmailer.mailer.smtp.transport.smtp.host` from container.

**Comment by fabpot** [comment]
Closing as this bundle is not maintained anymore.
