### ISSUE TITLE
How to define custom mailtransport

### ISSUE THREAD

**Issue by jeff1985** [symfony/swiftmailer-bundle#308]
I'm trying to write a custom mail transport but it seems that this is not possible in the newer versions of this bundle. 

When I try to define it in the config like this:
```
swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: 'queue'
```
and in services.yaml
```
swiftmailer.mailer.transport.queue:
      class: App\Email\EmailQueueTransport
```

I see:
```
In SwiftmailerTransportFactory.php line 71:

  Not a built-in Swiftmailer transport: queue.
```

If found this issue, https://github.com/symfony/swiftmailer-bundle/issues/298 which is similar but has been closed because of reference to other library. Also I found a similar issue in https://github.com/mailjet/MailjetSwiftMailer/issues/24 
It is similar to my case, however I have my own transport implementation, which I try to configure. 

Is it generally possible to configure custom mailtransport with this bundle? And if so, is there any documentation about this?

**Comment by OskarStark** [comment]
Hi Jeff,

am I allowed to ask which transport do you want to implement? Did you checked symfony/mailer instead of SwiftMailer? It is the newer mailer approach we use in Symfony and it also has a lot of working transports on Board 👍🏻
