### ISSUE TITLE
Monitoring the spooling queue?

### ISSUE THREAD

**Issue by Sgoettschkes** [symfony/swiftmailer-bundle#31]
I was wondering if there is any interest in a command which monitors the spooling queue, giving information about the number of items in the queue, the date of the item longest in the queue and so on.

Background: I would like to monitor my queue with Icinga and while writing a shell script solves this issue for now, having a command could be handy:
- In case of other spooling options, it might not be as easy as now to count the queue
- If the application moves the place for swiftmailer to store the mails, the monitoring breaks

I could implement this if there is interest in merging it back.

**Comment by fabpot** [comment]
Closing as this bundle does not accept new features anymore (Symfony Mailer is now the preferred email solution over Swiftmailer).
