### ISSUE TITLE
[Swiftmailer] swiftmailer.delivery_addresses is painful to use

### ISSUE THREAD

**Issue by acantepie** [symfony/swiftmailer-bundle#311]
Hello,

If you are in dev env, you probably want avoid sending email to unwanted recipient, so you configure swiftmailer like this :
```
swiftmailer:
    delivery_addresses: [ "%env(DELIVERY_ADDRESS)%" ]
```
But on other env, you want disable this config but you CAN'T using only .env vars :
```
DELIVERY_ADDRESS=null # doesn't work, no email will be sent
```
So you have to put swiftmailer config on config/packages/dev.
But if you doing that, you can't enable or disable email sending using only .env vars.

**Comment by stof** [comment]
The way the delivery address feature works in SwiftmailerBundle indeed does not support enabling or disabling the feature at runtime based on env placeholders. It needs to be known at compile-time (here, you always pass an array with one value at compile time, even though the value itself is not known until runtime).
Changing that would require a big refactoring. And given that SwiftmailerBundle is in maintenance mode (due to symfony/mailer replacing swiftmailer), I don't think such refactoring will be done.

**Comment by OskarStark** [comment]
What I do is using a mailcatcher in dev an test and always send the mail

**Comment by acantepie** [comment]
Ho okay, i didn't know the existence of symfony/mailer bundle now..
I will check, thanks for answer

**Comment by acantepie** [comment]
Ok, same problem with symfony/mailer component.

**Comment by stof** [comment]
@acantepie how does your config looks like with symfony/mailer ?

**Comment by acantepie** [comment]
same as swiftmailer :
```
framework:
  mailer:
    envelope:
      recipients: [ '%env(MAILER_RECIPIENT)%' ]
```
If env MAILER_RECIPIENT is not an email, you got an error.

```
framework:
  mailer:
    envelope:
      recipients: '%env(json:MAILER_RECIPIENT)%'
```
Doesn't work too, you got an error on container building.

**Comment by mklewitz** [comment]
Here's a workaround:

.env:
`# after changing DELIVERY_ADDRESS, you have to cache:clear
DELIVERY_ADDRESS=`

config/packages/swiftmailer.yaml
`swiftmailer:
    delivery_addresses: '%app_delivery_addresses%'`

add this to App\Kernel->configureContainer():
`        if (isset($_SERVER['DELIVERY_ADDRESS']) && (strlen($_SERVER['DELIVERY_ADDRESS']) > 0)) {
            $container->parameters()->set('app_delivery_addresses', [$_SERVER['DELIVERY_ADDRESS']]);
        } else {
            $container->parameters()->set('app_delivery_addresses', null);
        }`

**Comment by fabpot** [comment]
Closing as explained by @stof. Suggestion by @OskarStark is probably the way to go.
