### ISSUE TITLE
Broken: Travis CI - Pull Request

### ISSUE THREAD

**Issue by mklewitz** [symfony/swiftmailer-bundle#314]
I submitted pull request #313 yesterday. It was marked as broken by Travis CI. A closer look reveals that this is not because of my change, but because the travis build is broken at the very beginning of the process:

```
$ composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master
Changed current directory to /home/travis/.config/composer
                                                                               
  [RuntimeException]                                                           
  No composer.json present in the current directory (./composer.json), this m  
  ay be the cause of the following exception.                                  
```

My pull request is only a small change in EventListener/EmailSenderListener.php and doesn't even touch composer.json or any other file.

**Comment by fabpot** [comment]
Closing as this bundle is not maintained anymore.
