### ISSUE TITLE
Expected response code 250 but got code "421", with message "421 Timeout waiting for data from client.

### ISSUE THREAD

**Issue by pmoubed** [symfony/swiftmailer-bundle#39]
This happens when I use it with AWS and For Loop to send emails. I don't use spool.

**Comment by kgreen169** [comment]
It's 2018 and I am having this exact same problem.  I have tried multiple ways to get around this error.  Here is my latest
try {
            $sendSuccess .= $mailer->send($message, $failedRecipients);
        } catch (Swift_TransportException $ste) {
            $mailSuccess .= "<br />Caught Swift_TransportException ste calling mailer->send<br />";
            $mailSuccess .= $ste->getMessage();
            $mailSuccess .= "<br />End ste->getMessage.  Stoping transport<br/>";
            $mailer->getTransport()->stop();
            $sendSuccess .= $mailer->send($message, $failedRecipients);
        }
not sure if I am using ->stop correctly

Still got exception 
Expected response code 250 but got code "421", with message "421 4.7.0 Try again later, closing connection. (MAIL) k130-v6sm1483348itb.0 - gsmtp "\
