### ISSUE TITLE
error "profiler template does not exist" in web toolbar

### ISSUE THREAD

**Issue by craue** [symfony/swiftmailer-bundle#57]
With 83488073b04286d71dcfa7a8f12d1f2c0fb1294d (#46) I'm getting
**The profiler template "@Swiftmailer/Collector/swiftmailer.html.twig" for data collector "swiftmailer" does not exist.**
from the web toolbar on each page (regardless of mail being sent). I'm still using Symfony 2.1.12, if that matters.

**Comment by fabpot** [comment]
Closing this old issue, should be fixed now as deps are better handled now in Symfony.
