### ISSUE TITLE
If the EmailSenderListener returns an Exception, it's ignored

### ISSUE THREAD

**Issue by blowski** [symfony/swiftmailer-bundle#71]
With Swiftmailer, when an email is sent, the default behaviour is to spool it in memory and then do the actual send during the `kernel.terminate` event.

In https://github.com/symfony/SwiftmailerBundle/blob/master/EventListener/EmailSenderListener.php, if the `$spool->flushQueue()` method (line 50) raises an exception (such as the SMTP server is down or the credentials don't work) it's just ignored. I don't see it in the logs or get any kind of notification.

I figured that the easiest way around this is to do something like:

```
try {
    $spool->flushQueue($this->container->get(sprintf('swiftmailer.mailer.%s.transport.real', $name)));
} catch (\Swift_TransportException $ex) {
    $this->container->get('logger')->critical($ex->getMessage());
}
```

but I don't know enough about the Kernel to know if this will have any strange side effects.

Is this a good idea?

**Comment by romaricdrigon** [comment]
+1 for doing something/anything to improve the situation: at the moment, those exceptions won't be logged; but will crash the profiler so you don't see anything in Symfony2 debug toolbar.

**Comment by qdequippe** [comment]
+1
The result of $mailer->send($message) is always equals to 1 even if Swift_TransportException is raised. It's a big problem for us because we can't check if the email is really sent or not.

What do you think about (re)throw the exception with the log as below (https://github.com/symfony/swiftmailer-bundle/blob/master/EventListener/EmailSenderListener.php#L62):
```
try {
    $spool->flushQueue($this->container->get(sprintf('swiftmailer.mailer.%s.transport.real', $name)));
} catch (\Swift_TransportException $exception) {
    if (null !== $this->logger) {
         $this->logger->error(sprintf('Exception occurred while flushing email queue: %s', $exception->getMessage()));
     }
     throw $exception;
}
```

**Comment by fabpot** [comment]
Closing old issues.
