### ISSUE TITLE
Add a configuration option to set default "from" address

### ISSUE THREAD

**Issue by adamziel** [symfony/swiftmailer-bundle#94]
It would be really amazing if it was possible to specify e.g. "default_from_email" in config.yml that SwiftmailerBundle would use whenever no sender email was specified

**Comment by mkrauser** [comment]
I agree. This would be really nice.

+1

**Comment by AZielinski** [comment]
I submitted a pull request to swiftmailer, if it's merged I can proceed with this ticket too:
https://github.com/swiftmailer/swiftmailer/pull/588

**Comment by webdevilopers** [comment]
:+1:

**Comment by samanmohamadi** [comment]
:+1:

**Comment by FinesseRus** [comment]
You can use [this plugin](https://github.com/FinesseRus/SwiftMailerDefaultsPlugin) to set default from address for a `\Swift_Mailer` instance.

**Comment by fabpot** [comment]
This has been implemented in Symfony Mailer.
