### ISSUE TITLE
where is the changelog for this bundle?

### ISSUE THREAD

**Issue by cordoval** [symfony/swiftmailer-bundle#98]
i was curious if this is tracked in symfony/symfony because there is a bridge there for swiftmailer. However it is just rare that AsseticBundle has a changelog and an upgrade md files yet this one here does not have the same. Any reason for not having a set cc @stof @sstok? :older_man:

**Comment by stof** [comment]
well, I'm not the one who did the releases of this bundle. and the guy doing it probably has not written a changelog. This is bad though (we don't even have a readme btw)
