### ISSUE TITLE
Possibility to configure multiple delivery addresses

### ISSUE THREAD

**Issue by mhert** [symfony/swiftmailer-bundle#99]
It would be nice if I could configure more than one delivery address.

My idea is to add another config value:
swiftmailer:
     delivery_addresses: ["mail1@example.com", "mail2@example.com"]

**Comment by stof** [comment]
this would have to be supported inn swiftmailer first

**Comment by sstok** [comment]
It seems it is supported in Swiftmailer just not properly documented.
https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Plugins/RedirectingPlugin.php

**Comment by lokhman** [comment]
To preserve backwards compatibility it's better to keep the same configuration name but also allow array as a value. Can we implement this feature ASAP, as I don't see any possible way to set multiple addresses now (comma separated string does not seem to work)?

**Comment by sstok** [comment]
@lokhman Yes that possible, convert the configuration type to an ArrayNode (protype scalar) and add a beforeNormalization callback that transforms the string to an array :+1: 

http://symfony.com/doc/current/components/config/definition.html#normalization

```
    ->children()
        ->arrayNode('delivery_addresses')
            ->prototype('scalar')
            ->beforeNormalization()
                ->ifString()
                ->then(function ($v) { return array($v); })
            ->end()
        ->end()
    ->end()
```

**Comment by lokhman** [comment]
@sstok Yeah, this is possible if you explicitly amend the source code of Swiftmailer in your vendors, which is not what we kinda expect ;)

**Comment by stof** [comment]
@lokhman no, it is not better to keep the same configuration. It is actually much easier to implement a BC layer between the old and the new name than supporting both in the same name (because we won't be able to use the normal XML normalization for prototyped nodes)

**Comment by lokhman** [comment]
@stof Fair enough. Either way will do the job.

**Comment by valentin1448162** [comment]
It's now working using:
```
swiftmailer:
    delivery_address:
        - test1@mail.com
        - test2@mail.com
```
